# Generated by Django 4.1 on 2023-07-20 10:02

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 20, 10, 2, 11, 858063, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
