# Generated by Django 4.1 on 2023-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
