version: '3.1'

services:
  app:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./blog:/app
      - ./requirements:/requirements
      - ./scripts:/scripts

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
