# Generated by Django 4.1 on 2023-07-21 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(default="smtp.gmail.com", max_length=128)),
                ("port", models.IntegerField(default=587)),
                ("user", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                ("use_TSL", models.BooleanField(default=True)),
                ("use_SSL", models.BooleanField(default=False)),
                ("are_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnsentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("context", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
