# Generated by Django 4.1 on 2023-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailcredentials",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="emailcredentials",
            name="are_active",
            field=models.BooleanField(
                default=True,
                help_text="If False, those credentials won't be used to send emails",
            ),
        ),
    ]
