# Generated by Django 4.1 on 2023-07-21 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_rename_user_emailcredentials_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcredentials",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailcredentials",
            name="fail_silently",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailcredentials",
            name="timeout",
            field=models.IntegerField(
                default=3600,
                help_text="Timeout in seconds for blocking operations like the connection attempt",
            ),
        ),
        migrations.AddField(
            model_name="emailcredentials",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
