# Generated by Django 4.1 on 2023-07-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_remove_unsentemail_context_unsentemail_html_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unsentemail",
            name="reason",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
