# Generated by Django 4.1 on 2023-07-21 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_rename_use_ssl_emailcredentials_use_ssl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailcredentials",
            options={"verbose_name_plural": "Email Credentials"},
        ),
        migrations.AlterModelOptions(
            name="unsentemail",
            options={"verbose_name_plural": "Unsent Emails"},
        ),
        migrations.RenameField(
            model_name="emailcredentials",
            old_name="use_tsl",
            new_name="use_tls",
        ),
    ]
