# Generated by Django 4.1 on 2023-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
