# Generated by Django 4.1 on 2023-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="posts.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(to="posts.post"),
        ),
    ]
